### ISSUE TITLE
Implement sync over SSH

### ISSUE THREAD

**Issue by remram44** [remram44/syncfast#9]

**Comment by aral** [comment]
Hey @remram44, thanks for making/sharing this. I see there’s a WIP pull request for this that you were working on about seven months ago. How close is that to being completed?

A cross platform single-binary rsync would be awesome (especially for Windows folks).

**Comment by remram44** [comment]
I faced some difficulty with flow control (e.g. when to send commands versus data). I'm planning to revisit this at some point but it's not a priority, sorry.

**Comment by onny** [comment]
Does your tool support syncing from one server to an other? like `syncfast test@server1:dir test@server2:`
